# Generated by Django 2.0.3 on 2018-05-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20180414_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='current_location',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='email',
            name='number_of_attachment',
            field=models.SmallIntegerField(default=0),
        ),
    ]
