# Generated by Django 2.0.3 on 2018-05-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20180507_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.CharField(default='dd3f962d', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
