# Generated by Django 2.0.3 on 2018-05-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20180507_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.CharField(default='652ba02e3f3b4250', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
