# Generated by Django 2.0.3 on 2018-05-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_auto_20180507_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
