# Generated by Django 2.0.3 on 2018-05-07 07:13

from django.db import migrations, models
import django.utils.timezone
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_auto_20180507_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='id',
        ),
        migrations.AddField(
            model_name='email',
            name='md5sum',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='content',
            field=models.FileField(storage=uploader.models.EmailFileSystemStorage(location='temp-email-storage'), upload_to=''),
        ),
    ]
