# Generated by Django 2.0.3 on 2018-05-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_auto_20180507_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='md5sum',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
